runners:
  - name: "aws-amd64-runner"
    cloud: "aws"
    instance_type: "t2.2xlarge"
    machine_image: "ami-08d337ba030150f71"
    region: "us-east-1"
    preemptible: false
    labels:
      - "cirun-aws-amd64"
  - name: "aws-arm64-runner"
    cloud: "aws"
    instance_type: "t4g.2xlarge"
    machine_image: "ami-05d50447160398aa9"
    region: "us-east-1"
    preemptible: false
    labels:
      - "cirun-aws-arm64"
