[package]
name = "amphitheatre"
version = "0.1.0"
edition = "2021"
description = "Amphitheatre API Server"
license = "Apache-2.0"
authors = [
    "Eguo Wang <wangeguo@gmail.com>",
]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
axum = { version = "0.6", features = ["headers"] }
clap = { version = "4.0.29", features = ["derive", "env"] }
dotenv = "0.15.0"
futures = "0.3"
headers = "0.3"
kube = { version = "0.77.0", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.16.0", features = ["v1_25"] }
log = "0.4.17"
pin-project = "1.0.12"
sea-orm = { version = "0.10.5", features=["runtime-tokio-rustls", "sqlx-mysql"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.89"
tokio = { version = "1.22.0", features = ["full"] }
tokio-stream = "0.1"
tower = { version = "0.4.13", features = ["full"] }
tower-http = { version = "0.3.5", features = ["full"] }
tower_governor = { git = "https://github.com/benwis/tower-governor", rev="01e1a107" }
tracing-subscriber = "0.3.16"
utoipa = { version = "2", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "3", features = ["axum"] }
uuid = { version = "1.2.2", features = ["v4", "fast-rng", "macro-diagnostics"] }
