[package]
name = "amphitheatre"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
axum = { version = "0.5", features = ["headers"] }
futures = "0.3"
headers = "0.3"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.22.0", features = ["full"] }
tokio-stream = "0.1"
