[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/amphitheatre-app/amphitheatre"
authors = [
    "Eguo Wang <wangeguo@gmail.com>",
]

[workspace]
members = [
    "apiserver",
    "controllers",
    "crdgen",
    "resolver",
    "resources",
]

# https://doc.rust-lang.org/cargo/reference/workspaces.html#the-workspacedependencies-table
[workspace.dependencies]
anyhow = "1.0"
amp-common = { git = "https://github.com/amphitheatre-app/common" }
amp-resolver = { path = "resolver", version = "0.1.0" }
amp-resources = { path = "resources", version = "0.1.0" }
clap = { version = "4.0.29", features = ["derive", "env"] }
dotenv = "0.15.0"
futures = "0.3"
kube = { version = "0.77.0", default-features = false, features = ["runtime", "derive", "rustls-tls"] }
k8s-openapi = { version = "0.16.0", default-features = false, features = ["schemars", "v1_24"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.89"
serde_yaml = "0.9.14"
thiserror = "1.0"
tokio = { version = "1.22.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
url = "2.3.1"
