[workspace.package]
version = "0.9.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/amphitheatre-app/amphitheatre"
authors = [
    "Eguo Wang <wangeguo@gmail.com>",
]

[workspace]
resolver = "2"
members = [
    "apiserver",
    "controllers",
    "crdgen",
    "resolver",
    "resources",
    "syncer",
    "workflow",
]

# https://doc.rust-lang.org/cargo/reference/workspaces.html#the-workspacedependencies-table
[workspace.dependencies]
amp-builder = { path = "builder" }
amp-common = { git = "https://github.com/amphitheatre-app/common", tag = "v0.9.0" }
amp-resolver = { path = "resolver" }
amp-resources = { path = "resources" }
amp-workflow = { path = "workflow" }
anyhow = "1.0.82"
async-nats = "0.35.1"
async-trait = "0.1.80"
clap = { version = "4.5.4", features = ["derive", "env"] }
dotenv = "0.15.0"
futures = "0.3.30"
k8s-openapi = { version = "0.22.0", default-features = false, features = ["schemars", "v1_30"] }
kube = { version = "0.91.0", default-features = false, features = ["runtime", "derive", "rustls-tls"] }
lazy_static = "1.4.0"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.116"
serde_yaml = "0.9.34+deprecated"
thiserror = "1.0.61"
tokio = { version = "1.37.0", features = ["full"] }
toml = "0.8.12"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
url = "2.5.0"
