[workspace.package]
version = "0.4.2"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/amphitheatre-app/amphitheatre"
authors = [
    "Eguo Wang <wangeguo@gmail.com>",
]

[workspace]
members = [
    "apiserver",
    "controllers",
    "crdgen",
    "resolver",
    "resources",
    "syncer",
]

# https://doc.rust-lang.org/cargo/reference/workspaces.html#the-workspacedependencies-table
[workspace.dependencies]
anyhow = "1.0"
amp-common = { git = "https://github.com/amphitheatre-app/common", tag = "v0.3.4" }
amp-resolver = { path = "resolver" }
amp-resources = { path = "resources" }
async-nats = "0.29.0"
clap = { version = "4.0.29", features = ["derive", "env"] }
dotenv = "0.15.0"
futures = "0.3"
kube = { version = "0.83.0", default-features = false, features = ["runtime", "derive", "rustls-tls"] }
k8s-openapi = { version = "0.18.0", default-features = false, features = ["schemars", "v1_26"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.89"
serde_yaml = "0.9.14"
thiserror = "1.0.43"
tokio = { version = "1.22.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
url = "2.3.1"
