[workspace.package]
version = "0.9.2"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/amphitheatre-app/amphitheatre"
authors = [
    "Eguo Wang <wangeguo@gmail.com>",
]

[workspace]
resolver = "2"
members = [
    "apiserver",
    "controllers",
    "crdgen",
    "resolver",
    "resources",
    "syncer",
    "workflow",
]

# https://doc.rust-lang.org/cargo/reference/workspaces.html#the-workspacedependencies-table
[workspace.dependencies]
amp-builder = { path = "builder" }
amp-common = { git = "https://github.com/amphitheatre-app/common", tag = "v0.9.3" }
amp-resolver = { path = "resolver" }
amp-resources = { path = "resources" }
amp-workflow = { path = "workflow" }
anyhow = "1.0.90"
async-nats = "0.37.0"
async-trait = "0.1.83"
axum = { version = "0.7.7" }
chrono = "0.4.38"
clap = { version = "4.5.19", features = ["derive", "env"] }
dotenv = "0.15.0"
futures = "0.3.31"
k8s-metrics = "0.19.0"
k8s-openapi = { version = "0.23.0", default-features = false, features = ["schemars", "latest"] }
kube = { version = "0.96.0", default-features = false, features = ["runtime", "derive", "rustls-tls"] }
lazy_static = "1.5.0"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
serde_yaml = "0.9.34+deprecated"
sha2 = "0.10.8"
tar = "0.4.42"
tempfile = "3.13.0"
thiserror = "1.0.67"
tokio = { version = "1.41.0", features = ["full"] }
tokio-stream = "0.1"
toml = "0.8.15"
tower-http = { version = "0.6.1", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
url = "2.5.2"
utoipa = { version = "5.1.3", features = ["axum_extras", "uuid", "chrono", "macros"] }
utoipa-swagger-ui = { version = "8.0.3", features = ["axum", "reqwest"] }
uuid = { version = "1.11.0", features = ["serde", "v4", "fast-rng", "macro-diagnostics"] }
