[workspace.package]
version = "0.6.10"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/amphitheatre-app/amphitheatre"
authors = [
    "Eguo Wang <wangeguo@gmail.com>",
]

[workspace]
resolver = "2"
members = [
    "apiserver",
    "controllers",
    "crdgen",
    "resolver",
    "resources",
    "syncer",
]

# https://doc.rust-lang.org/cargo/reference/workspaces.html#the-workspacedependencies-table
[workspace.dependencies]
anyhow = "1.0"
amp-common = { git = "https://github.com/amphitheatre-app/common", tag = "v0.5.6" }
amp-resolver = { path = "resolver" }
amp-resources = { path = "resources" }
async-nats = "0.33.0"
clap = { version = "4.4.10", features = ["derive", "env"] }
dotenv = "0.15.0"
futures = "0.3"
kube = { version = "0.87.1", default-features = false, features = ["runtime", "derive", "rustls-tls"] }
k8s-openapi = { version = "0.20.0", default-features = false, features = ["schemars", "v1_28"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9.27"
thiserror = "1.0.50"
tokio = { version = "1.34.0", features = ["full"] }
toml = "0.8.8"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
url = "2.4.1"
