[package]
name = "amp-apiserver"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Amphitheatre API Server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "amphitheatre"
path = "src/lib.rs"

[dependencies]
amp-common.workspace = true
amp-resources.workspace = true
async-nats.workspace = true
anyhow.workspace = true
axum = { version = "0.7.3" }
clap.workspace = true
dotenv.workspace = true
futures.workspace = true
headers = "0.4"
kube.workspace = true
k8s-openapi.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-stream = "0.1"
tower = { version = "0.4.13", features = ["full"] }
tower-http = { version = "0.5.1", features = ["full"] }
tracing.workspace = true
tracing-subscriber.workspace = true
utoipa = { version = "4.1.0", features = ["axum_extras", "uuid", "chrono"] }
utoipa-swagger-ui = { version = "6.0.0", features = ["axum"] }
uuid = { version = "1.6.1", features = ["serde", "v4", "fast-rng", "macro-diagnostics"] }
url.workspace = true
chrono = "0.4.31"
