[package]
name = "amp-apiserver"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Amphitheatre API Server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "amphitheatre"
path = "src/lib.rs"

[dependencies]
amp-common = { workspace = true, optional = false }
amp-resources = { workspace = true, optional = false }
async-nats = { workspace = true, optional = false }
anyhow = { workspace = true, optional = false }
axum = { version = "0.6", features = ["headers"] }
clap = { workspace = true, optional = false }
dotenv = { workspace = true, optional = false }
futures = { workspace = true, optional = false }
headers = "0.3"
kube = { workspace = true, optional = false }
k8s-openapi = { workspace = true, optional = false }
serde = { workspace = true, optional = false }
serde_json = { workspace = true, optional = false }
serde_yaml = { workspace = true, optional = false }
thiserror = { workspace = true, optional = false }
tokio = { workspace = true, optional = false }
tokio-stream = "0.1"
tower = { version = "0.4.13", features = ["full"] }
tower-http = { version = "0.4.4", features = ["full"] }
tower_governor = { git = "https://github.com/benwis/tower-governor", rev="01e1a107" }
tracing = { workspace = true, optional = false }
tracing-subscriber = { workspace = true, optional = false }
utoipa = { version = "4", features = ["axum_extras", "uuid", "chrono"] }
utoipa-swagger-ui = { version = "3", features = ["axum"] }
uuid = { version = "1.4.1", features = ["serde", "v4", "fast-rng", "macro-diagnostics"] }
url = { workspace = true, optional = false }
chrono = "0.4.31"
