name: Build & Publish Images

on:
  release:
    types: [published]

jobs:
  build-and-push-image:
    name: Build & Push Image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - bin: amp-apiserver
            dockerfile: ./apiserver/Dockerfile
          - bin: amp-controllers
            dockerfile: ./controllers/Dockerfile

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ matrix.bin }}

    - name: Build and push image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ${{ matrix.dockerfile }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: true
