name: Build Release Binaries

on:
  push:
    tags:
      - v[0-9]+.*

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    name: Upload Assets
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        bin: [amp-apiserver, amp-controllers, amp-crdgen, amp-syncer]
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: taiki-e/upload-rust-binary-action@v1
      with:
        bin: ${{ matrix.bin }}
        target: ${{ matrix.target }}
        token: ${{ secrets.GITHUB_TOKEN }}
