name: Build Release Binaries

on:
  push:
    tags:
      - v[0-9]+.*

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: nightly-2022-12-01

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        with:
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    name: Upload Assets
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ env.RUST_TOOLCHAIN }}
    - uses: taiki-e/upload-rust-binary-action@v1
      with:
        bin: amp-apiserver, amp-controllers, amp-crdgen
        target: ${{ matrix.target }}
        token: ${{ secrets.GITHUB_TOKEN }}
